import { ToggleSideMenu, SaveAuthData, AddBasicInfo, Logout } from "./";

export enum ActionTypes {
  LOGIN_DETAILS = "LOGIN_DETAILS",
  LOGOUT = "LOGOUT",
  TOGGLE_MENU = "TOGGLE_MENU",
  ADD_BASIC_INFO = "ADD_BASIC_INFO",
  REGISTER_STAFF_ASSETS = "REGISTER_STAFF_ASSETS",
  ASSIGN_STAFF_ASSETS = "ASSIGN_STAFF_ASSETS",
  SET_PLACEMENT_LIST = "SET_PLACEMENT_LIST",
  UPDATE_PLACEMENT_DATA = "UPDATE_PLACEMENT_DATA",
  CHANGE_PLACEMENT_STATUS = "CHANGE_PLACEMENT_STATUS",
  GET_ALL_POSITIONS = "GET_ALL_POSITIONS",
  GET_ALL_TERMINATION = "GET_ALL_TERMINATION",
  UPDATE_TERMINATION = "UPDATE_TERMINATION",
}

export type Action = SaveAuthData | ToggleSideMenu | AddBasicInfo | Logout;
